version: v21.5.1

files:
  - .github/.kodiak.toml
  - .github/workflows/close-stale-prs.yaml
  - .github/workflows/codeql-analysis.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/verify-release.yaml
  
