name: Test

on:
  push:
    branches-ignore:
      - "main"

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install packages
        run: |
          yarn install

      - name: Install SWC
        run: |
          yarn global add @swc/core @swc/cli

      - name: Build
        run: |
          yarn build

      - name: Run unit tests
        run: |
          yarn test
        env:
          CI_TEST: true
